# TensorFlow basics

TensorFlow is an end-to-end platform for machine learning. It supports the following:

* Multidimensional-array based numeric computation (similar to <a href="https://numpy.org/" class="external">NumPy</a>.)
* GPU and distributed processing
* Automatic differentiation
* Model construction, training, and export
* And more

## Tensors (Constant)

TensorFlow operates on multidimensional arrays or _tensors_ represented as `tf.Tensor` objects. Here is a two-dimensional tensor:

The most important attributes of a `tf.Tensor` are its `shape` and `dtype`:

* `Tensor.shape`: tells you the size of the tensor along each of its axes.
* `Tensor.dtype`: tells you the type of all the elements in the tensor.

In [17]:
# Here is a "scalar" or "rank-0" tensor . A scalar contains a single value, and no "axes".

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [18]:
# A "vector" or "rank-1" tensor is like a list of values. A vector has one axis.

rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [19]:
# A "matrix" or "rank-2" tensor has two axes.

rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [21]:
# Tensors may have more axes; here is a tensor with three axes

rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [24]:
import numpy as np

# You can convert a tensor to a NumPy array


np.array(rank_3_tensor)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)

In [1]:
import tensorflow as tf

tensor_1 = tf.constant([[1, 2.3, 3.],
                 [4, 5, 6]])

print(tensor_1)
print(tensor_1.shape)
print(tensor_1.dtype)

tf.Tensor(
[[1.  2.3 3. ]
 [4.  5.  6. ]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [2]:
tensor_2 = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

print(tensor_2)
print(tensor_2.shape)
print(tensor_2.dtype)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
<dtype: 'int32'>


In [3]:
tensor_3 = tf.constant([[15, 23, 3],
                 [4, 5, 6]],dtype=tf.float32)

print(tensor_3)
print(tensor_3.shape)
print(tensor_3.dtype)

tf.Tensor(
[[15. 23.  3.]
 [ 4.  5.  6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


TensorFlow implements standard mathematical operations on tensors, as well as many operations specialized for machine learning.

For example:

In [4]:
tensor_1 + tensor_3

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[16. , 25.3,  6. ],
       [ 8. , 10. , 12. ]], dtype=float32)>

In [5]:
5 * tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5. , 11.5, 15. ],
       [20. , 25. , 30. ]], dtype=float32)>

In [6]:
tf.transpose(tensor_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1. , 4. ],
       [2.3, 5. ],
       [3. , 6. ]], dtype=float32)>

In [7]:
tensor_1 @ tf.transpose(tensor_1)  # Matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[15.29, 33.5 ],
       [33.5 , 77.  ]], dtype=float32)>

In [8]:
tf.matmul(tensor_1, tf.transpose(tensor_1))  # Matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[15.29, 33.5 ],
       [33.5 , 77.  ]], dtype=float32)>

In [9]:
tf.concat([tensor_1, tensor_3], axis=0)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1. ,  2.3,  3. ],
       [ 4. ,  5. ,  6. ],
       [15. , 23. ,  3. ],
       [ 4. ,  5. ,  6. ]], dtype=float32)>

In [10]:
'''
In TensorFlow, tf.nn is a module that provides neural network-related operations
and functions. It stands for "neural network." This module includes a variety of
functions commonly used in building neural networks, such as activation functions,
loss functions, and other operations relevant to neural network modeling.
'''


"""
It's important to note that the tf.nn module is part of the lower-level API in
TensorFlow, and with the introduction of TensorFlow 2.x, many of these functions
are also available in the higher-level tf.keras.layers module, making it more
convenient for building and training neural networks.
"""

tf.nn.softmax(tensor_1, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.08293007, 0.304295  , 0.6127749 ],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [11]:
"""
calculates the sum of all elements in tensor_1. If tensor_1 is a multi-dimensional
tensor, the tf.reduce_sum function will sum across all dimensions, effectively
flattening the tensor.
"""
tf.reduce_sum(tensor_1)

<tf.Tensor: shape=(), dtype=float32, numpy=21.3>

Note: Typically, anywhere a TensorFlow function expects a `Tensor` as input, the function will also accept anything that can be converted to a `Tensor` using `tf.convert_to_tensor`. See below for an example.

In [12]:
aa = tf.convert_to_tensor([1,2,3])
print(aa)
print(aa.dtype)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<dtype: 'int32'>


In [13]:
tf.reduce_sum([1,2,3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

## Variables

Normal `tf.Tensor` objects are immutable. To store model weights (or other mutable state) in TensorFlow use a `tf.Variable`.

In [14]:
var_1 = tf.Variable([0, 1.70, 0])
var_1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0. , 1.7, 0. ], dtype=float32)>

In [15]:
var_1.assign([1, 2, 3])
var_1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [16]:
var_1.assign_add([1, 5, 1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([2., 7., 4.], dtype=float32)>

In [27]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

In [30]:
my_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [31]:
bool_variable

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False, False, False,  True])>

In [32]:
complex_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>

In [28]:
print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


In [29]:
print("A variable:", my_variable)
print("\nViewed as a tensor:", tf.convert_to_tensor(my_variable))
print("\nIndex of highest value:", tf.math.argmax(my_variable))

# This creates a new tensor; it does not reshape the variable.
print("\nCopying and reshaping: ", tf.reshape(my_variable, [1,4]))

A variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)

Copying and reshaping:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)
